alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- alerts/*.yml
scrape_configs:
- job_name: terragon-moe
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - terragon-moe-service:80
