apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: terragon-moe-router
  name: terragon-moe-router
  namespace: terragon-moe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: terragon-moe-router
  template:
    metadata:
      labels:
        app: terragon-moe-router
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: terragon-config
        image: terragon/moe-router:v4.0
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        name: terragon-moe
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
