apiVersion: v1
kind: Service
metadata:
  name: terragon-moe-service
  namespace: terragon-moe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: terragon-moe-router
  type: ClusterIP
