# Default evolution configuration for MoE routing discovery

evolution:
  population_size: 100
  generations: 1000
  mutation_rate: 0.1
  crossover_rate: 0.7
  
  selection:
    method: "tournament"
    tournament_size: 3
    elitism: true
    elite_fraction: 0.1
  
  termination:
    max_generations: 1000
    fitness_threshold: 0.95
    stagnation_limit: 50

objectives:
  - name: "accuracy"
    weight: 1.0
    target: 0.95
    minimize: false
    
  - name: "latency"
    weight: -0.2
    target: 10  # milliseconds
    minimize: true
    
  - name: "sparsity"
    weight: 0.1
    target: 0.9
    minimize: false
    
  - name: "load_balance"
    weight: 0.15
    target: 0.8
    minimize: false

topology:
  num_experts: 16
  sparsity_range: [0.05, 0.3]
  min_expert_usage: 0.1
  max_active_experts: 4
  
routing:
  temperature_range: [0.1, 5.0]
  top_k_range: [1, 4]
  load_balancing_weight: 0.01
  diversity_weight: 0.1

hardware:
  target_device: "auto"  # auto, cpu, cuda
  memory_limit: "4GB"
  batch_size: 32
  precision: "fp32"  # fp32, fp16, int8

logging:
  level: "INFO"
  log_evolution: true
  log_interval: 10
  save_checkpoints: true
  checkpoint_interval: 50