env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  build-and-push:
    if: github.event_name == "push" && github.ref == "refs/heads/main"
    needs: test
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.production
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{
          env.IMAGE_NAME }}:v4.0
  deploy:
    environment: production
    if: github.event_name == "push" && github.ref == "refs/heads/main"
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest -v --cov=.
    - name: Run quality gates
      run: python3 comprehensive_quality_gates.py
name: TERRAGON MoE Router CI/CD
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - develop
